project_structure:
  contracts: contracts


compiler:
  solc:
    optimizer:
      enabled: true
      runs: 800
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.3'
      - '@gnosis.pm=gnosis/safe-contracts@1.3.0'

    